### ISSUE TITLE
encoder elements should allow for charset elements

### ISSUE THREAD

**Issue by lhoekenga** [enricopulatzo/logback-XSD#14]
Currently, the only "encoder" sub-element supported by this schema is "pattern".  "encoder" elements support an optional "charset" sub-element, e.g.

        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <charset>UTF-8</charset>
            <pattern>%msg%n</pattern>
        </encoder>

**Comment by enricopulatzo** [comment]
Sorry for taking so long! I'm looking for someone to take this repo over if you're interested @nkatsar

**Comment by nkatsar** [comment]
Thank you for the feedback, not sure if I can take this over but as a collaborator I can try to help with the issues.
