### ISSUE TITLE
Merge with nkatsar’s fork?

### ISSUE THREAD

**Issue by oliviercailloux** [enricopulatzo/logback-XSD#31]
Would you please consider merging with the [fork](https://github.com/nkatsar/logback-XSD) done by nkatsar? As far as I can see it has some valuable additions…

**Comment by enricopulatzo** [comment]
Honestly I'm happy to give up this repo. I've not actually done anything with it since 2014.

**Comment by oliviercailloux** [comment]
I see… Then hopefully nkatsar will merge the [commits](https://github.com/enricopulatzo/logback-XSD/commits/master) that have happened here since 2015!
Thanks.

**Comment by enricopulatzo** [comment]
I've cleared out my pull request backlog! It's like a git-merge Christmas!
